# Generated by Django 2.0.6 on 2018-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('os', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=10)),
                ('data_transfer', models.IntegerField()),
                ('processor_speed', models.IntegerField()),
            ],
        ),
    ]
